"""initial schema

Revision ID: 067f9f8305f6
Revises: 
Create Date: 2026-07-04 19:02:43.670799
"""
from alembic import op
import sqlalchemy as sa


revision = '067f9f8305f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=True),
    sa.Column('funcscan_version', sa.String(length=64), nullable=True),
    sa.Column('source_dir', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_label'), ['label'], unique=False)

    op.create_table('provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('sample_key', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('file_checksum', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_version', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provenance', schema=None) as batch_op:
        batch_op.create_index('ix_prov_checksum', ['sample_key', 'file_checksum'], unique=False)
        batch_op.create_index('ix_prov_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_key', sa.String(length=255), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('annotation_tool', sa.String(length=32), nullable=True),
    sa.Column('n_contigs', sa.Integer(), nullable=False),
    sa.Column('n_genes', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('track_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_key', 'release_id', name='uq_sample_release')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_samples_sample_key'), ['sample_key'], unique=False)

    op.create_table('genes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('gene_key', sa.String(length=255), nullable=False),
    sa.Column('contig', sa.String(length=255), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=1), nullable=True),
    sa.Column('feature_type', sa.String(length=32), nullable=False),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genes', schema=None) as batch_op:
        batch_op.create_index('ix_genes_key', ['gene_key'], unique=False)
        batch_op.create_index('ix_genes_locus', ['sample_id', 'contig', 'start', 'end'], unique=False)
        batch_op.create_index('ix_genes_product', ['product'], unique=False)

    op.create_table('cazyme_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('cazy_family', sa.String(length=64), nullable=False),
    sa.Column('ec_number', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=32), nullable=True),
    sa.Column('n_tools_support', sa.Integer(), nullable=True),
    sa.Column('substrate', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cazyme_annotations', schema=None) as batch_op:
        batch_op.create_index('ix_cazyme_family', ['cazy_family'], unique=False)

    op.create_table('interpro_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.String(length=64), nullable=True),
    sa.Column('signature_acc', sa.String(length=128), nullable=True),
    sa.Column('signature_desc', sa.Text(), nullable=True),
    sa.Column('interpro_acc', sa.String(length=64), nullable=True),
    sa.Column('interpro_desc', sa.Text(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('evalue', sa.Float(), nullable=True),
    sa.Column('go_terms', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interpro_domains', schema=None) as batch_op:
        batch_op.create_index('ix_interpro_acc', ['interpro_acc'], unique=False)
        batch_op.create_index('ix_interpro_sig', ['signature_acc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpro_domains', schema=None) as batch_op:
        batch_op.drop_index('ix_interpro_sig')
        batch_op.drop_index('ix_interpro_acc')

    op.drop_table('interpro_domains')
    with op.batch_alter_table('cazyme_annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_cazyme_family')

    op.drop_table('cazyme_annotations')
    with op.batch_alter_table('genes', schema=None) as batch_op:
        batch_op.drop_index('ix_genes_product')
        batch_op.drop_index('ix_genes_locus')
        batch_op.drop_index('ix_genes_key')

    op.drop_table('genes')
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_sample_key'))

    op.drop_table('samples')
    with op.batch_alter_table('provenance', schema=None) as batch_op:
        batch_op.drop_index('ix_prov_entity')
        batch_op.drop_index('ix_prov_checksum')

    op.drop_table('provenance')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_label'))

    op.drop_table('releases')
    # ### end Alembic commands ###
